name: MSD
run-name: MSD
on: [push]
jobs:
  MSD:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: chmod +x setup_build.sh
      - run: sudo ./setup_build.sh
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: ./infra/deploy.sh -p ./infra/deploy.parameters.json
