name: MSD
run-name: MSD
on: [push]
jobs:
  MSD:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: chmod +x setup_build.sh
      - run: ./setup_build.sh
      - run: ./infra/deploy.sh -p ./infra/deploy.parameters.json
